# Generated by Django 2.2.28 on 2023-01-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressoosqpfoaie'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressoosqpfoaie',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
